### PR TITLE
Many UI improvements!

### PR DESCRIPTION
**Pull request by avaidyam**
* Inline Authorization dialog instead of prompt()
* Support for HTTP Basic auth (with obscured password field)
* Support for free-form server variables
* Merged response body/status codes table
* Added support for x-code-samples if present
* Added operationId to demo panel

### CODE REVIEW

**Comment by bourdakos1** [comment]
Great work! I will test out locally, but I think this looks good. Thanks for all the help @avaidyam

**Comment by avaidyam** [comment]
@bourdakos1 No problem! Once you've merged this PR, could you push to npm? (Alternatively I can PR a GitHub Action workflow for it)

**Comment by bourdakos1** [comment]
A github action would be beyond amazing thank you ❤️❤️❤️

**Comment by avaidyam** [comment]
@bourdakos1 Since you would need to create the Action, here's the workflow file: 

`.github/workflows/publish.yml`:
```yaml
name: Publish
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Autoincrement version
        run: |
          # from refs/tags/v1.2.3 get 1.2.3
          VERSION=$(echo $GITHUB_REF | sed 's#.*/##')
          npm version --no-git-tag-version $VERSION
        shell: bash
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
```

You'll need to add the `NPM_AUTH_TOKEN` secret to the repository. Also, I'm not quite sure how your repo is set up for building and publishing an npm package so you may need to change the steps (and perhaps remove `npm test`?).

**Comment by avaidyam** [comment]
@bourdakos1 Done! See #18.

**Pull request merged**
