### PR TITLE
fix: make plugin compatible with Docusaurus beta.13

### LINKED ISSUE #87: Use of Docusaurus Constants has changed
On Docusaurus Beta 13 they seem to have done changes and now the plugin is broken with error:
```
Error: Cannot find module '@docusaurus/core/lib/constants'
Require stack:
- /home/anthony/safe_docs/safe/docs/node_modules/docusaurus-plugin-openapi/dist/index.js
- /home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/server/plugins/init.js
- /home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/server/plugins/index.js
- /home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/server/index.js
- /home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/commands/build.js
- /home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/index.js
- /home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/bin/docusaurus.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/anthony/safe_docs/safe/docs/node_modules/docusaurus-plugin-openapi/dist/index.js:25:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at module.exports (/home/anthony/safe_docs/safe/docs/node_modules/import-fresh/index.js:32:59)
    at normalizePluginConfig (/home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:46:61)
    at /home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:138:40
    at Array.map (<anonymous>)
    at initPlugins (/home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:134:10)
    at loadPlugins (/home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/server/plugins/index.js:55:40)
```

The Docusaurus constants have been moded to `@docusaurus/utils`.

Please see: https://github.com/facebook/docusaurus/discussions/6099

### PR DESCRIPTION
**Pull request by Josh-Cena**
Fix #87. See https://github.com/facebook/docusaurus/pull/6047. This change was made in the core to resolve circular dependencies. Sorry for not marking it as breaking change—we aren't expecting anyone to use such implementation detail (at least previously). As now it's found its home in utils, we can assert that it will be stable as long as the architecture isn't completely overhauled.

### CODE REVIEW

**Comment by bourdakos1** [comment]
Haha no worries, I assumed importing directly from the lib folder would be fragile and have unannounced breaking changes. I appreciate the PR ❤️

**Comment by Josh-Cena** [comment]
This is hard 🤦‍♂️ Because of https://github.com/facebook/docusaurus/issues/6087 the theme fails to build, but in fact the TS files aren't even used, so no idea why they are checked by TS... I tried `skipLibCheck` with no luck. If this project is using Yarn berry I would suggest doing a patch package

**Comment by bourdakos1** [comment]
@Josh-Cena Oh, wow thanks for all the work you've put in to this! I think I can fix the typescript issue. I'll checkout your branch and see if I can get it working

**Comment by Josh-Cena** [comment]
Oh hehe, I did add `declare module` for the theme but I forgot to add it to the preset... Thanks for the fix

**Comment by bourdakos1** [comment]
No problem :) Thanks for everything you've done, really appreciate it

**Review by bourdakos1 — APPROVED** [review]

**Pull request merged**
